# Generated by Django 5.2.1 on 2025-05-10 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TR', 'Triple Riding'), ('RL', 'Red Light Jump'), ('SP', 'Speeding')], max_length=2)),
                ('image', models.ImageField(upload_to='violations/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violations.violationreport')),
            ],
        ),
    ]
